# This composes file is intended for Development services
services:
  postgres:
    container_name: dev_postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: dev_redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  pg_data: